### ISSUE TITLE
get_cell_type_info error

### ISSUE THREAD

**Issue by camerongw** [dmcable/RCTD#1]
I'm currently trying to run RCTD on some slide-seq v2 data and am running into trouble with the init_RCTD function. I've figured out that the error is coming from within the get_cell_type_info function, in the get_cell_mean function. I'm getting:

Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0

But I can't figure out why 'dims' is of length 0, or which step of get_cell_mean is producing this error.
I am running this with CELL_MIN set to 1 just for testing purposes.
Any comments on why this might be happening would be appreciated.

**Comment by dmcable** [comment]
Hey Cameron,

I'm not completely sure exactly what happened, but it is possible that setting CELL_MIN to 1 created a weird edge case in which selecting a single cell produced an object of different dimensions than selecting multiple cells. I would recommend setting CELL_MIN to at least 2. If that does not fix the issue, then I would recommend looking in the input of `get_cell_type_info` to see if `cell_types` contains at least two of each cell type. Please keep me updated on what ultimately was causing this issue.

Best,
Dylan

**Comment by dmcable** [comment]
And if you have cell types with less than CELL_MIN instances, you should remove those cell types from the single cell reference Seurat object. Not advisable to use a cell type with less than 25 instances.
