### ISSUE TITLE
use of log in computing logFC in the get_de_genes function

### ISSUE THREAD

**Issue by lihaone** [dmcable/RCTD#16]
Hey Dylan, 
Thanks for the great package. 
I'm new to single cell analysis, but noticed in the "get_de_genes" function that you used the natural logarithm "log" to compute the fold change of genes. 

    logFC = log(cell_type_info[[1]][gene_list,cell_type] + epsilon) - log(other_mean + epsilon)

Was this on purpose? What's the rationale behind this? Since as far as I know, people often use log2 when computing fold changes when analyzing bulk data. Thanks!
Hao

**Comment by dmcable** [comment]
Dear Hao,

Thank you, and sorry for the late reply. I think I agree with you that log2 might have been a better choice, and I will keep this in mind in the future. If you want, you can convert between log2 and log_e by multiplying by log_e(2).

Dylan
