### ISSUE TITLE
read.SpatialRNA() function

### ISSUE THREAD

**Issue by KacDom** [dmcable/RCTD#17]
Hi,

I've been recently ussing your package and I'm really liking it but  I think I might have stumbled upon a small bug with 
the read.SpatialRNA() function. I'm using indexed spot names (spot1, spot2 etc.) and I've noticed that the function ignores first column with spatial data and starts with the second spot. It much easier to see when using indexed spot names like I am. Adding empty column (after the column with gene names) resolves the problem.

I'm using RCTD version from two months ago so perhaps the bug is already fixed.

Regards,
KacDom

**Comment by dmcable** [comment]
Dear KacDom,

I am sorry that I am just getting around to this. Yes, I have encountered this issue in the past, and thanks for bringing this to my attention. I am actually working on a new version in which the SpatialRNA data is not read in from csv files, but rather from R objects (i.e. matrices or data.frames). I believe this will solve this issue in the future, but I am glad you have been able to get around the issue.

Dylan
