### ISSUE TITLE
Error in create.RCTD with 1 platform deg left

### ISSUE THREAD

**Issue by simoncmo** [dmcable/RCTD#19]
Hi,

It seem like the create.RCTD will generate error message when there's only one platform deg left. 
Seemingly due to the filtering step in restrict_counts. At puck = restrict_counts(puck, gene_list_bulk, UMI_thresh = config$UMI_min, UMI_max = config$UMI_max)
When gene_list_bulk have only 1 gene left, puck@counts[gene_list, keep_loc] becomes a numeric vector and cause issue when trying to be assign to puck@counts, a dgCMatrix. 
A special case but just wanna point out so hopefully it can be handled by the script. 

Thanks,
Simon

**Comment by dmcable** [comment]
Dear Simon,

Thanks for raising the issue, and I am quite sorry for the late reply. Can you please provide more clarification for this issue? In particular, do you mean the case in which there is 1 gene, or the case in which there is 1 pixel or sample? I could see both causing an issue. In the case where there is 1 gene, could you please explain the use case? 

Happy to look more into this issue. Thank you.

Best,
Dylan

**Comment by simoncmo** [comment]
Hi Dylan,

Thanks for getting back to and sorry for the late reply. For me it was 1 gene left after filtering steps (multiple pixels/dots/spots) that cases this exceptions. There wasn't much use case here I'd say, since not much inference can be made with one gene I believe. So to me I was hoping there's a warning message or certain filtering step ahead to catch those cell type/clusters with insufficient DEGs left. Other than causing issue downstream at this step.
But that being said I have noticed you guys have been updated the tool quite a bit and this might have been handled anyway (kudos for that.. while my old script doesn't work anymore lol) 
So yeah if that's the case that's great. I haven't had a chance to rerun the tool in the newer version but if I ran into this again I will report back with more details.

Thanks,
Simon

**Comment by dmcable** [comment]
Ok, thank you Simon! Yes, please report again if this issue persists and is reproducible in the current version. I agree with you that ideally there should be more than 1 gene present, and an error message would be appropriate in that scenario.

Best,
Dylan
