### ISSUE TITLE
Using get_decomposed_data with Visium

### ISSUE THREAD

**Issue by skinnider** [dmcable/RCTD#21]
Hi Dylan - thanks for this amazing package, I am getting some great results for cell type deconvolution in my Visium dataset that clearly outperform what I’ve been able to achieve with other approaches so far.

Beyond deconvolution, I was also fascinated by Fig. 6 of your paper because the specific dataset I am working on also seems to have a within-cell-type spatial gradient, which we have been struggling to understand so far. I have been reading through the vignette, documentation, and analysis script at https://raw.githack.com/dmcable/RCTD/dev/AnalysisPaper/MainFigures/figure6-spatialgenes.html but I am struggling a bit to figure out how (if?) the code in the markdown file can be applied to a Visium dataset.

As I understand it, the `get_decomposed_data` function works on two objects - `results_df` and `weights_doublet` - that are only found in the `results` object when `run.RCTD` is called with `doublet_mode = TRUE`. However, I also understood from the paper that doublet_mode should be set to FALSE with Visium. 

Have I misunderstood something? Or is there an easy workaround for extracting the decomposed matrix without setting doublet_mode=TRUE? 

Thanks in advance.

**Comment by dmcable** [comment]
Hello, thank you for the feedback, and sorry for the late reply -- I got busy with my coursework.

Yes, you are correct for noticing that after running RCTD, we have a method to compute the expected counts assigned to each cell type at each pixel for each gene. 

It is also true as you pointed out, that `get_decomposed_data` was implemented for doublet mode. However, there is nothing fundamentally different about extending this method to `doublet_mode = "full"`. 

Please see the 'Expected cell-type-specific gene expression' section of our methods in our paper:

![Screen Shot 2021-03-27 at 7 44 46 AM](https://user-images.githubusercontent.com/40443769/112719671-64c66f00-8ed0-11eb-8467-74f4e4c0176f.png)

You should be able to compute these values from the RCTD results. Y is your original counts matrix, Beta is the RCTD `@weights`matrix, and Mu is the reference cell type profiles matrix (found in `@cell_type_info$renorm[[1]]`. After obtaining these matrices, the expected cell type-specific gene expression should be obtainable in a for loop. 

I hope this helps, and please let me know if you have any questions.
