### ISSUE TITLE
"cell_type_names" can not omit.

### ISSUE THREAD

**Issue by JMnotDGR** [dmcable/RCTD#27]
Hi.
This is a great method. However, I have found a small bug in the source code. Due to this, I can not run the test case successfully.
In the RTCD.R, in the 3th line, define the function 'process_cell_type_info', the parameter 'cell_type_names' is necessary. 
3th:  process_cell_type_info <- function(reference, cell_type_names, CELL_MIN = 25) 
However, in the 45th line, ’cell_type_names‘ is not given.
45th:  cell_type_info <- list(info = process_cell_type_info(reference, CELL_MIN = CELL_MIN_INSTANCE), renorm = NULL)
In my program is error here.
Can you check it? 
Thanks a lot.

**Comment by asifzubair** [comment]
Running into the same problem here ...

**Comment by dmcable** [comment]
Yes, it should be fixed in a recent Pull request, thank you.
