### ISSUE TITLE
Using log-transformed expression matrix for the reference data

### ISSUE THREAD

**Issue by gorkemkose** [dmcable/RCTD#28]
Hi, is it possible to use an expression matrix where the values are log-transformed for the creation of the reference object somehow? Back-transforming the expression matrix to a count-level untransformed matrix is tricky and my annotated reference dataset directly supplies the transformed expression matrix. Is there a way for that? Thanks in advance!

**Comment by dmcable** [comment]
Hello -- unfortunately we do require the original expression matrix. As you mentioned, back transformation is tricky, so we wouldn't know the best way to properly handle a transformed matrix. If the transformation is e.g. Log(counts per million + offset), then reversing should be possible if you can figure out the exact way the matrix was generated. Sorry that I don't have a way to solve the problem without the original counts.

**Comment by gorkemkose** [comment]
Thanks for the reply! I'll figure that out :)
