### ISSUE TITLE
Error with read.VisiumSpatialRNA

### ISSUE THREAD

**Issue by FPetitprez** [dmcable/RCTD#29]
Hello and congratulations for this nice tool.
I am trying to use it on my Visium data, but I cannot import the visium dataset as a SpatialRNA, and I get the following output with this error:

── Column specification ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
cols(
  barcodes = col_character(),
  in_tissue = col_double(),
  x = col_double(),
  y = col_double(),
  pxl_col_in_fullres = col_double(),
  pxl_row_in_fullres = col_double()
)

Error in check_coords(coords) : 
  SpatialRNA: the second dimension of coords is not 2. Please enforce that dim(coords)[2] == 2 (x and y coordinates).
In addition: Warning message:
In sparseMatrix(i = indices[] + 1, p = indptr[], x = as.numeric(x = counts[]),  :
  'giveCsparse' has been deprecated; setting 'repr = "T"' for you

I tried with several visium samples, always with the same error.
What do you think can cause this error?

Thanks in advance.
Best,
Florent

**Comment by FPetitprez** [comment]
Looking at the code of the read.VisiumSpatialRNA() function, the coords table that is given to SpatialRNA() has 5 columns ("in tissue", "x", "y", "pxl_col_in_fullres", "pxl_row_in_fullres"). I modified locally this function so that it only sends the "x" and "y" columns to SpatialRNA(). Is this correct?

**Comment by dmcable** [comment]
yes, exactly, I have fixed this error as well. thank you.
