### ISSUE TITLE
Automated plots generated

### ISSUE THREAD

**Issue by amasden** [dmcable/RCTD#30]
Thank you for developing great Spatial deconvolution tool!
I'm new to this field so I have a couple of questions;;

plot_weights: What threshold is applied?
                        Does the threshold mean spots with proportion of interested cell type over that are visualized?
                        and how can I control the threshold?

plot_weights_unthreshold: Threshold 0 meaning that zero proportion
                                              if some spots are not visualized with interested cell type?

plot_cond_occur: What criteria is applied to confident pixel?

**Comment by dmcable** [comment]
Thank you, and sure thing.

For doublet_mode, `plot_weights_doublets` is recommended.

For full_mode, `plot_weights` or `plot_weights_unthreshold` would be recommended. The threshold used is meant to be a reasonable choice, but different thresholds should be applied in different scenarios. 

The threshold used in `plot_weights` is UMI dependent:

```
#min weight to be considered a singlet as a function of nUMI
UMI_cutoff <- function(nUMI) {
  return (pmax(0.25, 2 - log(nUMI,2) / 5))
}
```
You may control the threshold by either (1) creating your own version of the `plot_weights` function with your desired threshold (2) filtering the spots according to your criteria before passing into a plotting function. 

For `plot_weights_unthreshold`, all spots will be plotted, with color displaying the weight ranging from 0 to 1.

The criteria in `plot_cond_occur` is the same as in `plot_weights`. 

Thank you.
