### ISSUE TITLE
Reconstructing the dataset from AnalysisPaper repo

### ISSUE THREAD

**Issue by hiraksarkar** [dmcable/RCTD#31]
Hi,

Thanks for writing such an amazing tool (and paper), I was trying to generate the dataset from this [script]( https://github.com/dmcable/RCTD/blob/master/AnalysisPaper/MainFigures/figure1.Rmd). The files `myRCTD_cer.rds` or the predecessor `puckCropped.RDS` do not seem to be produced by any of the scripts explicitly. 

Please let me know if I am missing any of the scripts. 

To elaborate my major concern is constructing the `puck@cell_labels`, `SpatialRNA` does not explicitly use `cell_labels` argument, any idea how do I prepare that in order to run the script in [figure1.Rmd](https://github.com/dmcable/RCTD/blob/master/AnalysisPaper/MainFigures/figure1.Rmd)

https://github.com/dmcable/RCTD/blob/master/R/classes.R#L31 suggests that there is no slot `cell_labels` although, the document string suggests that there is a `cell_labels` slot in https://github.com/dmcable/RCTD/blob/master/R/classes.R#L25

Best,
Hirak

**Comment by dmcable** [comment]
Hi Hirak,

Thank you for your interest -- I think the difficulty comes from the current version of RCTD being different from the original used at the time of writing the paper. You are correct that `cell_labels` is no longer used. I would recommend creating a variable to represent the cell_labels independent of the SpatialRNA object.

I have uploaded these objects that you mentioned at this link, which will be available for 7 days: https://we.tl/t-04j2zkqnEo

Hope this helps!

Dylan

**Comment by hiraksarkar** [comment]
Hi @dmcable 

Thanks a lot for your prompt reply. What should be the best way to select the `cell_labels`, Is it `argmax` on the weight? e.g. something like following, 

```
results <- myRCTD@results
puck_cell_labels <- colnames(results$weights)[apply(results$weights,1,which.max)]
```
Is there a pipeline that I could follow to regenerate the objects? An additional question is, how did you crop the cerebellum puck, is there a tool for doing that?

**Comment by dmcable** [comment]
Hello, 

It depends on if you are doing full mode or doublet/multi mode (see https://raw.githack.com/dmcable/RCTD/dev/vignettes/spatial-transcriptomics.html). In general, RCTD assigns cell type proportions, so there could be multiple cell types per pixel. 

For doublet mode, cell labels are stored in results$results_df object, and for full mode, the closest thing would be taking the argmax, but there could still be other cell types present on each pixel. 

Best,
Dylan

**Comment by dmcable** [comment]
I use the `gatepoints` package for cropping -- this is the script I use for hand-selected cropping:

```
library(gatepoints)
X <- puck@coords
pal = colorRampPalette(c("blue", "red"))
dforder = findInterval(puck@nUMI, sort(puck@nUMI))
plot(X, pch=20, col=pal(nrow(X))[dforder], cex = 0.5)
selectedPoints <- fhs(X, mark = TRUE,  pch=20, col=pal(nrow(X))[dforder], cex = 0.5)
arr <- as.integer(names(puck@nUMI) %in% selectedPoints); names(arr) <- names(puck@nUMI)
RCTD::plot_puck_continuous(puck, names(puck@nUMI), arr, ylimit = c(-1,2))
puckCropped = restrict_puck(puck,names(which(arr == 1)))
saveRDS(puckCropped,file.path(datadir,'puckCropped.rds'))
```

**Comment by hiraksarkar** [comment]
Hi @dmcable ,

Thanks a lot for the reply.
