### ISSUE TITLE
Retrieval of the reference data

### ISSUE THREAD

**Issue by gorkemkose** [dmcable/RCTD#32]
Hello, thanks for the amazing and still easily understandable tool! 

I have a question: Where did you get the reference data from? I'll get the scRNA-seq data from GEO and converting it into the required format for RCTD is not an easy task for me :) What would you recommend for that? 

Thanks in advance!
Görkem

**Comment by hiraksarkar** [comment]
Hi @gorkemkose ,

I generally use the following steps, not sure if this is exactly the steps followed by @dmcable (Please correct me if I am wrong). The reference files can be obtained from [here](https://singlecell.broadinstitute.org/single_cell/study/SCP948/robust-decomposition-of-cell-type-mixtures-in-spatial-transcriptomics#study-download) (you need to log in to get data)

reading the snRNA-seq reference
```{r}
refdir <- "/home/hsarkar/code/deconv_benchmark/data/RCDT_experiment/SCP948/"
reference <- readRDS(file.path(refdir,"scRefSubsampled1000_cerebellum_singlenucleus.RDS"))
```
Clean the reference to run RCDT
```{r}
meta_data <- reference@meta.data
cell_types <- meta_data$liger_ident_coarse; names(cell_types) <- rownames(meta_data)

nUMI <- meta_data$nUMI ; names(nUMI) <- rownames(meta_data)

ref_counts <- reference@assays$RNA@counts
rcdt_reference <- Reference(ref_counts, cell_types, nUMI)
```
Best
Hirak

**Comment by gorkemkose** [comment]
Hi @hiraksarkar ,

Thanks for the reply! I think your steps are pretty much the same as what is provided in the Vignettes. But my question was actually a little bit different. Since there are different platforms that the datasets are provided, I had struggled to convert them into the format used by @dmcable . The data looks so neat! :) But I hope I'm on my way to figure it out. Again, thanks for the reply and also the dataset!

Best,
Görkem

**Comment by hiraksarkar** [comment]
Hi @gorkemkose ,

Great to hear that you figured it out. Please post a notebook/gist of the steps that you are taking. Would be really helpful. 

Thanks
Hirak

**Comment by gorkemkose** [comment]
Hi @hiraksarkar ,

I will definitely post a notebook when I handle the datasets from different platforms, for now we only focused on a dataset coming from 10X. When I post it, definitely let you know! 

Best,
Görkem

**Comment by dmcable** [comment]
Hi @gorkemkose ,

Thank you for your question -- I use something pretty similar to the steps outlined above -- for the counts matrix usually it reads in as something similar to a matrix. For the UMI and cell type vectors, it just depends on where that information is stored, but then accessing it and putting it in a vector. Sometime the nUMI is just the sum of all the counts for each pixel.
