### ISSUE TITLE
cell types are removed during the construction of the reference

### ISSUE THREAD

**Issue by riverliao** [dmcable/RCTD#34]
Hi,

I am facing a problem on losing the cell types when decomposing my spatial data. Actually, I have 25 reference cell types when loading the data prepared for constructing the reference data, and also 1874 spatial pixels to be decomposed. However, the final output only contains weights for about 500 pixels corresponding to18 cell types per pixel. The following is my code (essentially setting a full mode based on my case), could you take a look at this? Thanks .

library(RCTD)
library(Matrix)
refdir <- "/nfs/turbo/umms-welchjd/riverlrh/data_delete" # directory for the reference
counts <- read.csv(file.path(refdir,"dge.csv")) # load in counts matrix
rownames(counts) <- counts[,1] 
counts[,1] <- NULL # Move first column to rownames
meta_data <- read.csv(file.path(refdir,"meta_data.csv"))
cell_types <- meta_data$cluster
names(cell_types) <- meta_data$barcode # create cell_types named list
cell_types <- as.factor(cell_types) # convert to factor data type
nUMI <- meta_data$nUMI
names(nUMI) <- meta_data$barcode # create nUMI named list
### Create the Reference object
reference <- Reference(counts, cell_types, nUMI)
## Examine reference object (optional)
print(dim(reference@counts)) #observe Digital Gene Expression matrix
###
puck<-readRDS(file="/nfs/turbo/umms-welchjd/riverlrh/slurm/puck.RDS")
## Examine SpatialRNA object (optional)
print(dim(puck@counts)) # observe Digital Gene Expression matrix
print(head(puck@coords)) # start of coordinate data.frame
barcodes <- colnames(puck@counts) # pixels to be used (a list of barcode names). 
myRCTD <- create.RCTD(puck, reference, max_cores = 1)
myRCTD <- run.RCTD(myRCTD, doublet_mode = 'full')
#
results <- myRCTD@results
raw_weights = as.matrix(results$weights)
write.csv(raw_weights,file="/home/riverlrh/my_RCTD_weights.csv")
saveRDS(results, file.path(refdir,'results.rds'))

**Comment by dmcable** [comment]
Hi River, 

Can you please include the output of your results? In particular, could you output `table(cell_types)` and `table(reference@cell_types)`? That way we can check if all cell types are present. Thanks!

Best,
Dylan

**Comment by dmcable** [comment]
Please reopen this issue if you would like to discuss further, thank you!
