### ISSUE TITLE
Problem about regression differentially expressed genes

### ISSUE THREAD

**Issue by denizcangi** [dmcable/RCTD#35]
Dear RCTD developers,

I am working on to use your package to deconvolute the single cell data and spatial informatics data using reference data obtained from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE114727 and spatial data obtained from https://support.10xgenomics.com/spatial-gene-expression/datasets/1.2.0/Parent_Visium_Human_BreastCancer

The main problem of mine is, when I tried to create the RCTD object with create.RCTD, with giving my reference and spatialRNA object, it gave an error such as it couldn't find any regression differentially expressed gene.

Here is the data I have used to create the RCTD object and steps that I have followed with guidance from the vignette.

I have a count matrix, this is tiny part of the counts matrix, the row names are the genes and column names are the barcodes:
<img width="513" alt="Screen Shot 2021-05-10 at 13 29 21" src="https://user-images.githubusercontent.com/74117454/117651213-5f7c6580-b19a-11eb-911f-6d18bda9de95.png">

Also I have meta_data as mentioned in the vignettes that looks like this:
<img width="330" alt="Screen Shot 2021-05-10 at 13 36 08" src="https://user-images.githubusercontent.com/74117454/117651268-715e0880-b19a-11eb-9a48-ffd28d69ae36.png">

Then I have created cell_types list as it mentioned in the vignettes which looks like:
<img width="448" alt="Screen Shot 2021-05-10 at 13 41 12" src="https://user-images.githubusercontent.com/74117454/117651385-8f2b6d80-b19a-11eb-8e3e-7b65e9a4a32d.png">
<img width="348" alt="Screen Shot 2021-05-10 at 14 18 47" src="https://user-images.githubusercontent.com/74117454/117651466-a5392e00-b19a-11eb-97e7-27d6e4dc876f.png">

In meta data I don't have nUMI information so I have created the reference object without this information and reference object looks like:

Slot "cell_types":
<img width="484" alt="Screen Shot 2021-05-10 at 13 45 08" src="https://user-images.githubusercontent.com/74117454/117651609-cd289180-b19a-11eb-98e9-4b3c845682ff.png">

Slot "counts":
<img width="1012" alt="Screen Shot 2021-05-10 at 13 45 22" src="https://user-images.githubusercontent.com/74117454/117651634-d6b1f980-b19a-11eb-937a-88cb04fe737a.png">

Slot "nUMI":
<img width="481" alt="Screen Shot 2021-05-10 at 13 45 34" src="https://user-images.githubusercontent.com/74117454/117651675-e4677f00-b19a-11eb-81a8-82f009951f78.png">

<img width="562" alt="Screen Shot 2021-05-10 at 14 25 32" src="https://user-images.githubusercontent.com/74117454/117652240-97d07380-b19b-11eb-9b07-cfd95bcd7968.png">

After creating the Reference object I have created the SpatialRNA object with counts data as:
<img width="493" alt="Screen Shot 2021-05-10 at 13 57 42" src="https://user-images.githubusercontent.com/74117454/117651775-006b2080-b19b-11eb-8da2-f70b061a15cb.png">

And coords data as:
<img width="272" alt="Screen Shot 2021-05-10 at 14 00 07" src="https://user-images.githubusercontent.com/74117454/117651819-0e20a600-b19b-11eb-8b45-2a268628451c.png">

After that created the puck and moved on to creating RCTD object:
<img width="582" alt="Screen Shot 2021-05-10 at 14 22 25" src="https://user-images.githubusercontent.com/74117454/117651919-35777300-b19b-11eb-822a-f558000eabcd.png">

As it can be seen it gave an error such as **0 regression differentially expressed genes found.**
Can you guide me to resolve this error?

Thanks in advance,
Deniz

**Comment by dmcable** [comment]
Hi @gorkemkose @denizcangi 

I think the issue could be caused if the genes do not completely match between the spatial data and the reference data. Could you please check the intersection between the two sets of genes? Thanks.

**Comment by dmcable** [comment]
I have added a line of code to check for the error of two gene sets not intersecting, as others have also had that issue. If that is indeed the error, please standardize your gene names to match between spatial data and reference.

**Comment by dmcable** [comment]
Please reopen this issue if you would like to discuss further, thank you!
