### ISSUE TITLE
Missing return object in the `get_norm_ref` function

### ISSUE THREAD

**Issue by zuoyi93** [dmcable/RCTD#37]
Hi Dr. Cable,

I think the `get_norm_ref` function here is missing an object to return.

https://github.com/dmcable/RCTD/blob/e74fa3e612bf396cf0e4ce1f08abf9444fbf9082/R/processRef.R#L53-L58

I suppose you'd want to return `cell_type_means_renorm`? Also the documentation of this function might need an update: the output should be a data frame, not a list, right?

Best,

Yi

**Comment by dmcable** [comment]
Thanks, the documentation typo has been fixed! In R, if there is no return statement, by default the last evaluated expression will be returned, so `cell_type_means_renorm` is already returned.
