### ISSUE TITLE
could not find function "get_decomposed_data"

### ISSUE THREAD

**Issue by drli** [dmcable/RCTD#38]
I was trying to compute expected cell type-specific gene expression using  "get_decomposed_data"

>hsc_gene_expression <- get_decomposed_data(results$results_df, hsc_genes, puckA, results$weights_doublet, cell_type_info)

Error in get_decomposed_data(results$results_df, hsc_genes, puckA, results$weights_doublet,  :
  could not find function "get_decomposed_data"

Any suggestions?

**Comment by dmcable** [comment]
Just made the function exported. The function should be accessible now -- please note that now results$results_df should be removed from the parameter list. Best of luck!
