### ISSUE TITLE
DE genes for cell-types

### ISSUE THREAD

**Issue by Roopali24** [dmcable/RCTD#39]
Hi,

I have a question regarding the DE genes produced by RCTD. I can see that the list of DE genes is saved in myRCTD@internal_vars$gene_list_reg but I want to know which of the genes are specific to a certain cell type as the output shows things like:
[1] "get_de_genes: Astrocytes found DE genes: 176"
[1] "get_de_genes: Bergmann found DE genes: 232"
[1] "get_de_genes: Choroid found DE genes: 217"
[1] "get_de_genes: Endothelial found DE genes: 354"

So I want to know those Astrocyte or Endothelial specific genes and not just the total DE genes. Can you please tell me if that information is saved with the results.

Thank you,
Roopali

**Comment by dmcable** [comment]
Hi Roopali,

This information isn't used directly by RCTD; however, it is possible to access this information. The gene expression matrix is in `myRCTD@cell_type_info$info[[1]]`. There, for each gene you can tell which cell type expresses it the most. Alternatively, you can use the get_marker_data function, as in the following script:

https://raw.githack.com/dmcable/RCTD/dev/AnalysisPaper/MainFigures/figure4.html

In this case, you could call: `get_marker_data(myRCTD@cell_type_info$info[[2]], myRCTD@cell_type_info$info[[1]], myRCTD@internal_vars$gene_list_bulk)`

Hope this helps!
