### ISSUE TITLE
The function in simulating doublets

### ISSUE THREAD

**Issue by yl883** [dmcable/RCTD#40]
Hi! I am trying to understand how the doublets are simulated. 
I saw a function called "sub_sample_cell" in "doubletsimulation.R" but didn't find its definition:
firstbeads[,index] = as.vector(sub_sample_cell(iv$gene_list, restrict_test_ref@assays$RNA@counts, firstInd, UMI1))
Could you explain what this function is?
Thank you!

**Comment by dmcable** [comment]
Hi, this function is last used in an earlier commit of RCTD. Please see: https://github.com/dmcable/RCTD/blob/51890f8fe3d2e152d3c6ea87f4ffd99d30d3f16b/R/slideseq_sim.R

This function sub-samples the counts on the cell at random to a fixed number of total UMIs.

Please let me know if you have any other questions!

**Comment by yl883** [comment]
Thanks a lot!
