### ISSUE TITLE
Options or any suggestions for the better mapping

### ISSUE THREAD

**Issue by JihyunKim1108** [dmcable/RCTD#41]
Dear RCTD developers,

I am currently working on integration spatial data with single-cell reference datasets.
I think RCTD is very useful integration tool for my dataset. However, some of my cell types don't seem to be perfectly mapped as I think.

To do a better integration implementation, I made some changes to my single cell object and implemented RCTD with some parameter changes.

1. Reduced single-cell object features(genes) while keeping some highly variable genes (eg. top 100 HVGs, top 500 HVGs, top 600 HVGs)
2. Used scRFE (single-cell identity definition using random forests and recursive feature elimination) to get discriminative genes which could be helpful for my integration and reduced features of single cell object.
3. Some changes in gene_cutoff, fc_cutoff, gene_cutoff_reg, fc_cutoff_reg

However, I think all these options could not drastically changed my integration results.

Can you suggest me some other parameters or some things for the better mappping?

Thanks,
Ji hyun

**Comment by dmcable** [comment]
Hi Ji hyun,

Thank you for you message and your thoughtful optimizations to improve RCTD results. I agree with your intuition that better gene selection is perhaps the most critical decision. For example, when using the default gene selection of RCTD, you would want to play around with the parameters gene_cutoff, fc_cutoff, gene_cutoff_reg, fc_cutoff_reg to ensure that some marker genes are selected for each cell type (i.e. 100 per cell type). Additionally, the total DE genes used (for the second step, not bulk) can be around 2,000 to 3,000. In the past, these considerations have yielded the best results; although, for some datasets, we have used fewer (1,000 genes or even 150 genes for MERFISH). 

I would suggest plotting cell type calls against metagenes or marker genes (i.e. add together all the marker genes for each cell type). By plotting the marker genes, you should clearly see which pixels _should_ be called as a certain cell type. If they are not called as that cell type, you can then investigate why they were not called as that cell type. For example, see the next paragraph.

One possible issue can be cell type certainty. RCTD may think something is a cell type but not have enough confidence to call it (and as a result rejecting the pixel). This may be if there is some similar cell type that RCTD can not distinguish. If two cell types are very similar, you can either (1) combine them in the same class using the `class_df` option or (2) merge the two subtypes into one cell type. In general, if you have many subtypes, you could try using broader classes of cell types. Alternatively, you can change the parameters for thresholds for certainty -- this would be `QL_score_cutoff = 10` and `doublet_like_cutoff = 25` within the `process_bead_doublet` function. By reducing these parameters, RCTD will more aggressively make cell type calls.

You can also try other modes of RCTD -- doublet_mode, full_mode, multi_mode, some of which may be better suited for your dataset.

I hope this helps!

Best,
Dylan

**Comment by JihyunKim1108** [comment]
Thank you so much for your thoughtful response!
