### ISSUE TITLE
Not all spots can be mapped

### ISSUE THREAD

**Issue by TerminatorJ** [dmcable/RCTD#42]
Dear developer:
    This is a very fast and accurate tool for cell deconvolution as I know. but I am still confused about the result from 'full mode' and 'multi mode'. I input 3000 spots, however, after running RCTD, I just got 2976 spots which have the weight results. I want to know what did that mean? Why RCTD cannot assign a cell type proportion to those spots? due to data quality?

**Comment by dmcable** [comment]
Hello, most likely spots were pre-filtered due to number of UMIs. Default is to subset to spots with >= 100 UMIs (there is also a maximum value). This default threshold can be changed if you would like.

**Comment by TerminatorJ** [comment]
Thank you for your quick reply
