### ISSUE TITLE
different between multi mode and full mode

### ISSUE THREAD

**Issue by TerminatorJ** [dmcable/RCTD#43]
I found "full mode" and "multi mode" are quite similar, whereas "sub_weights" of multi-mode results may come from adding some thresholds to remove false positive spots. 
Can I use the results from sub_weights to visualize the spots? or we should only use all-weights which gives proportion values to all cell types?

**Comment by dmcable** [comment]
Hello, `all_weights` is the result of full-mode; when you run RCTD on any mode (including multi-mode), it still reports the results of full-mode. 

For the multi-mode results, you should use `sub_weights`. The difference is that in full-mode, all cell types are used and get a weight, whereas in multi-mode, the algorithm iteratively selects a subset of cell types that are likely to be on the pixel.
