### ISSUE TITLE
Data availability - hippocampus cell type labels

### ISSUE THREAD

**Issue by lmweber** [dmcable/RCTD#44]
Hi, I am trying to reproduce some of the results in Figures 5 and 6 of your paper -- specifically to obtain the predicted cell type labels per spot from RCTD for the hippocampus dataset, as shown in Figure 5A.

I am especially interested in the CA3 labels, which are also used in Figure 6D.

I think I have found all the code and raw data to re-run RCTD to generate these predicted cell type labels, but I was wondering if the labels are also available directly in a separate data object, either in the Broad repo or somewhere else.

If these cell type labels are available, could you please let me know how to obtain them? Thank you!

**Comment by dmcable** [comment]
Dear Lukas,

Thanks for reaching out -- I just sent to your email the RData object containing these cell type labels and weights.

-Dylan

**Comment by lmweber** [comment]
Great, thank you for the quick response!
