### ISSUE TITLE
Why only 71 spots left when running RCTD example data

### ISSUE THREAD

**Issue by eleozzr** [dmcable/RCTD#46]
Hi, Dylan Cable,
I followed the tutorial https://github.com/dmcable/RCTD/blob/master/vignettes/spatial-transcriptomics.Rmd to run RCTD. The number of spots for spatial transcriptomics is 100, but after running  `run.RCTD`  function, I only get 71 spots and I cannot figure it out. 
```r
myRCTD <- create.RCTD(puck, reference, max_cores = 1)
myRCTD <- run.RCTD(myRCTD, doublet_mode = 'doublet')

dim(myRCTD@results$results_df)
#[1] 71  9
 dim(myRCTD@results$weights)
#[1] 71 19
```
Any comments would be helpful. Thanks.

**Comment by eleozzr** [comment]
Sorry for that.  I figured it out.  When creating an RCTD object by `create.RCTD`, the internal function will filter out low-quality spots.

**Comment by Yijia-Jiang** [comment]
@dmcable Hello, what is the difference between filtering min_UMI and filtering min_counts? Isn't gene counts the same as number of UMI per spot?
