### ISSUE TITLE
Is it possible that Reference use normalized gene expression matrix instead of counts for reference 

### ISSUE THREAD

**Issue by lengfei5** [dmcable/RCTD#49]
Hi there,

I am trying to use RCTD to deconvolve cell type of Visium data, but unfortunately my reference data are from different batches with non-overlapping cell types. I would like to integrate them first to have an unified and comprehensive reference. 
However, after batch correction, I have corrected gene expression and no UMI counts anymore, which seems to be not accepted by the Reference function in RCTD. 

Is it correct that only the normalized gene expression of reference is used in the modeling part. 

It would be nice that the Reference function can take normalized gene matrix as input as well. 

Thank you in advance.

Best,

**Comment by JZL** [comment]
Hi,

Not a RCTD dev but I use it a lot. You're right, more or less, that it quickly transitions to only using the normalzed avg vectors coming from `process_cell_type_info` - https://sourcegraph.com/github.com/dmcable/RCTD@a2cc391f5bf3f56c5175ec6297425293f50deeed/-/blob/R/RCTD.R?L47:34&subtree=true (although you have to be a little wary when it does its own variable gene selection)

Depending on how comfortable you are slightly modifying the library you can control the reference input to RCTD pretty comprehensively. In particular, look at https://sourcegraph.com/github.com/dmcable/RCTD/-/blob/R/processRef.R?L22-23&subtree=true where it first normalizes the reference and then averages the cell clusters.You could write a custom function which doesn't UMI normalize (or even just accepts immediately the 'matrix-of-avgs').  =You can even create your own S4 `Reference` class and bypass all the checks. 

The one worry is that this normalization needs to be compatible with the puck's normalization so they map well. The normalization as written is equivalent to Seurat's RC relative counts normalization (but note the default scale.factor in Seurat is 1000 not RCTD's 1, that really threw me). So each cell sums to 1 -  you'd want to be careful about your own custom normalization.

Thanks
Jonah

**Comment by dmcable** [comment]
Hi Lingfei,

It's a great idea to pre-integrate multiple references together to obtain more cell types and better estimates across platforms.

I agree with what @JZL said! The easiest thing to try would be to pass your `corrected gene expression` to the RCTD `Reference` constructor function (with the option `require_int = FALSE`). The main thing is to ensure that the scale of the gene expression is in linear/raw expression space, rather than e.g. log-space. For example, counts per million, counts per thousand, counts etc should all be fine. The UMI counts can be calculated as the sum of expression across all genes, or it can be passed into `Reference` as `NULL`, and RCTD will calculated UMI as the sum across all genes.

Please try that, and let us know if you have any further issues or concerns!

Best,
Dylan

**Comment by lengfei5** [comment]
So great to have quick and great answers here.
Many thanks @JZL and @dmcable. 

@dmcable, Just to make sure I understand everything, the Reference function in RCTD actually accepts the corrected gene expression matrix as input as long as require_int = FALSE. 
Is there any other parameters I should change or not at all ?

This is really fantastic and I really love this package. 
Thanks again.

**Comment by dmcable** [comment]
Yes, that's exactly correct, shouldn't be any other parameter changes, and great to hear your feedback!

Best,
Dylan

**Comment by lengfei5** [comment]
This is awesome and thank you so much :)

**Comment by lengfei5** [comment]
Dear @dmcable ,

I have another question regarding the platform or batch effect normalization step in RCTD.
Do I need to make sure that the similar proportions of cell types in my reference and the Visium data, or at least comparable ? Or very different proportions of cell types in two datasets is not problem at all ?
Thanks.

Best,
Jingkui

**Comment by dmcable** [comment]
Hi Jingkui,

No need to consider the reference cell type proportions; the cell type proportions in the reference are not considered by RCTD. The platform effect normalization step of RCTD estimates the cell type proportions in the spatial dataset.

Best,
Dylan

**Comment by lengfei5** [comment]
Really cool and thanks again for the prompt answer, which is extremely helpful. 

Best,
Jingkui
