### ISSUE TITLE
Could not simulate the doublet dataset by doubletsimultion.R

### ISSUE THREAD

**Issue by Jinyu2019** [dmcable/RCTD#50]
In the folder AnalysisPaper/Rscripts/, I could not run the doublesimulation.R to produce simulated dataset. So could you provide the function sub_sample_cell( ) ?
Thanks.

**Comment by dmcable** [comment]
Hi,

This function is available in this file https://github.com/dmcable/RCTD/blob/master/AnalysisRCTDE/helper_functions/de_simulation_helper.R

Good luck!

Dylan
