### ISSUE TITLE
Run RCTD with 10x visium

### ISSUE THREAD

**Issue by r-melo** [dmcable/RCTD#6]
Hi,

Is it possible to run RCTD with 10 visium spatial transcriptomics instead of slideseq? In that case how should I change or adapt function read.SpatialRNA?

Thank you

**Comment by dmcable** [comment]
Yes, the function read.SpatialRNA reads in a dge matrix and coordinates matrix, both of which can be obtained from a Visium dataset.

**Comment by r-melo** [comment]
Thanks!
