### ISSUE TITLE
Error on sweep

### ISSUE THREAD

**Issue by r-melo** [dmcable/RCTD#8]
I'm following the tutorial using the cerebellum data, when I try to produce the plot I have the following error:
`> norm_weights = sweep(results$weights, 1, rowSums(results$weights), '/')`
> Error in rowSums(results$weights) : 
>   'x' must be an array of at least two dimensions

Just to complement
`dim(results$weights)`
>[1] 2347   11

Also, my weights are all the same, but I don't know if that is an issue.

**Comment by r-melo** [comment]
Also, my results are all the same, I believe because the weights are all the same

**Comment by dmcable** [comment]
I believe this error can be fixed by `library(Matrix)` before running this command.

The weights being the same indicates that something has gone wrong. Can you please paste the code used to run RCTD?

**Comment by dmcable** [comment]
Also, could you please screenshot the output messages of RCTD including the create.RCTD function? Also, please make sure that you run RCTD with test-mode = FALSE.

**Comment by r-melo** [comment]
Both issues solved. Somehow I missed the test-mode = T in my code. Thanks!
