### ISSUE TITLE
read.SpatialRNA not reading all cells.

### ISSUE THREAD

**Issue by r-melo** [dmcable/RCTD#9]
When I run read.SpatialRNA the final number of spots is one less than the total number. When I compare with the raw BeadLocationsForR.csv file, it seems the code is skipping the first spot.

> library(RCTD)
> library(Seurat)
> ref <- readRDS('test/1000cellsSubsampled_cerebellum_singlecell.RDS')
> spatial <- read.SpatialRNA('test/')
Parsed with column specification:
cols(
  barcodes = col_character(),
  xcoord = col_double(),
  ycoord = col_double()
)
Parsed with column specification:
cols(
  .default = col_double(),
  Row = col_character()
)
See spec(...) for full column specifications.
|================================================================| 100% 1740 MB
> bar <- read.csv('test/BeadLocationsForR.csv')
> which(!bar$barcodes %in% rownames(spatial@coords))
[1] 1
> bar$barcodes[1]
[1] CTTCCATGACATTT
39496 Levels: AAAAAAAAAAAGCC AAAAAAAAAAAGTG AAAAAAAAAGAGGA ... TTTTTTTTTTTTTT`

**Comment by dmcable** [comment]
The first row in the file is interpreted as a header containing gene names. I believe that will explain this.

**Comment by hxy265** [comment]
I also found this behaviour. I believe the issue is this line in the read.SpatialRNA function, it removes the first column which is a spot and not the gene names after the column_to_rownames conversion.
`counts = counts[,2:dim(counts)[2]]`

**Comment by hxy265** [comment]
thanks you!
